### PR TITLE
Bump dependencies + support Android adaptive icons

### PR DESCRIPTION
**Pull request by ottopic**

### CODE REVIEW

**Comment by igorsantos07** [comment]
@jasonkneen, any chance you could merge this in? Without it, the library is broken for many years already. People still use it.

**Comment by jasonkneen** [comment]
Done!

**Comment by igorsantos07** [comment]
@jasonkneen sorry for bothering again, but it haven't arrived at [NPM yet](https://www.npmjs.com/package/ticons), which still shows latest as 0.24.2. Not sure what's needed to update it there, though the last release here on GitHub is quite old...

**Comment by jasonkneen** [comment]
Done!

**Comment by igorsantos07** [comment]
Thank you so much sir! Have a wonderful weekend, a wonderful half of April and wonderful 2024 :joy:

**Pull request merged**
